#!/usr/bin/env python3
"""Generate decoded classic-renderer tiles and RGB palette from ROM images."""

from __future__ import annotations

import argparse
from pathlib import Path

GRAPHICS_SIZE = 0x2000
PROMS_SIZE = 0x200
PROM_HALF = 0x100


def read_exact(path: Path, size: int, label: str) -> bytes:
    data = path.read_bytes()
    if len(data) != size:
        raise ValueError(f"{label}: {path} is {len(data)} bytes, expected {size}")
    return data


def compute_channel(inputs: int) -> int:
    conductance = 1.0 / 100.0 + 1.0 / 270.0
    current = 5.0 / 100.0
    if (inputs & 0x01) == 0:
        conductance += 1.0 / 270.0
        current += 0.05 / 270.0
    if (inputs & 0x02) == 0:
        conductance += 1.0
        current += 0.05
    return int((current / conductance) * 255.0 / 5.0 + 0.4)


def clamp(value: int) -> int:
    return min(255, max(0, value))


def c_div(numerator: int, denominator: int) -> int:
    """Integer division truncated toward zero, matching the C renderer."""
    return numerator // denominator if numerator >= 0 else -((-numerator) // denominator)


def decode_palette(proms: bytes) -> list[tuple[int, int, int]]:
    low, high = proms[:PROM_HALF], proms[PROM_HALF:]
    raw = []
    luminance = []
    for address in range(128):
        red = compute_channel((low[address] & 0x01) | ((high[address] & 0x01) << 1))
        green = compute_channel(((low[address] >> 2) & 0x01) | (((high[address] >> 2) & 0x01) << 1))
        blue = compute_channel(((low[address] >> 1) & 0x01) | (((high[address] >> 1) & 0x01) << 1))
        raw.append((red, green, blue))
        luminance.append(299 * red + 587 * green + 114 * blue)
    minimum, maximum = min(luminance), max(luminance)
    palette = []
    for (red, green, blue), value in zip(raw, luminance):
        u = c_div((blue - value // 1000) * 492, 1000)
        v = c_div((red - value // 1000) * 877, 1000)
        target = ((value - minimum) * 256) // (maximum - minimum)
        palette.append((clamp(target + c_div(1140 * v, 1000)),
                        clamp(target - c_div(395 * u, 1000) - c_div(581 * v, 1000)),
                        clamp(target + c_div(2032 * u, 1000))))
    return palette


def decode_tiles(graphics: bytes, offset: int) -> list[list[int]]:
    tiles = []
    for tile in range(256):
        base = offset + tile * 8
        pixels = []
        for row in range(8):
            low, high = graphics[base + row], graphics[base + 0x800 + row]
            pixels.extend((((high >> (7 - column)) & 1) << 1 | ((low >> (7 - column)) & 1))
                           for column in range(8))
        tiles.append(pixels)
    return tiles


def render_tiles(name: str, tiles: list[list[int]]) -> list[str]:
    lines = [f"static const uint8_t {name}[256][64] = {{"]
    for pixels in tiles:
        lines.append("    {" + ", ".join(map(str, pixels)) + "},")
    lines.append("};")
    return lines


def render_header(graphics: bytes, proms: bytes) -> str:
    output = [
        "/* Generated by tools/generate_classic_render_assets.py; do not edit. */",
        "#ifndef PHOENIX_RENDER_ASSETS_H",
        "#define PHOENIX_RENDER_ASSETS_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct { uint8_t red; uint8_t green; uint8_t blue; } PhoenixRgb;",
        "static const PhoenixRgb phoenix_palette_rgb[128] = {",
    ]
    output.extend(f"    {{{red}, {green}, {blue}}}," for red, green, blue in decode_palette(proms))
    output.extend(["};", ""])
    output.extend(render_tiles("phoenix_background_tiles", decode_tiles(graphics, 0x0000)))
    output.append("")
    output.extend(render_tiles("phoenix_foreground_tiles", decode_tiles(graphics, 0x1000)))
    output.extend(["", "#endif", ""])
    return "\n".join(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--graphics", type=Path, required=True)
    parser.add_argument("--proms", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    graphics = read_exact(args.graphics, GRAPHICS_SIZE, "graphics ROM")
    proms = read_exact(args.proms, PROMS_SIZE, "colour PROM ROM")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_header(graphics, proms), encoding="ascii")


if __name__ == "__main__":
    main()
