#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#include <stdint.h>

/* Values stored in PhoenixState.GameState ($43A4). */
typedef enum {
    GAME_STATE_NEW_GAME = 0x00,
    GAME_STATE_SCORE_FLASH = 0x01,
    GAME_STATE_INIT_ROUND = 0x02,
    GAME_STATE_PLAYING = 0x03,
    GAME_STATE_PLAYER_EXPLODING = 0x04,
    GAME_STATE_GAME_OVER = 0x05,
    GAME_STATE_MOTHERSHIP_EXPLODING = 0x06,
    GAME_STATE_MOTHERSHIP_SCORE = 0x07,
} PhoenixGameState;

/* Low nibble of PhoenixState.LevelAndRound ($43B8), dispatched by L0800. */
enum {
    LEVEL_PATTERN_MASK = 0x0F,
    LEVEL_PATTERN_ALIENS_FADE_IN_0 = 0x00,
    LEVEL_PATTERN_ALIENS_ACTIVE_1 = 0x01,
    LEVEL_PATTERN_ALIENS_FADE_IN_2 = 0x02,
    LEVEL_PATTERN_ALIENS_ACTIVE_3 = 0x03,
    LEVEL_PATTERN_BIRDS_SPIRAL_4 = 0x04,
    LEVEL_PATTERN_BIRDS_FADE_IN_5 = 0x05,
    LEVEL_PATTERN_BIRDS_SPIRAL_6 = 0x06,
    LEVEL_PATTERN_BIRDS_FADE_IN_7 = 0x07,
    LEVEL_PATTERN_BIRDS_SPIRAL_8 = 0x08,
    LEVEL_PATTERN_MOTHERSHIP_FADE_IN_9 = 0x09,
    LEVEL_PATTERN_MOTHERSHIP_AND_ALIENS_A = 0x0A,
    LEVEL_PATTERN_ALIENS_ACTIVE_B = 0x0B,
};

enum {
    PLAYER_STATE_MOVEMENT_ENABLED = 0x08,
    SHIELD_DURATION_INITIAL = 0xFF,
};

#endif /* GAME_CONSTANTS_H */
