#!/usr/bin/env python3
"""Generate runtime-independent C2 hi-res glyph atlases from ROM images."""

import argparse
from pathlib import Path

GRAPHICS_SIZE = 0x2000
PROMS_SIZE = 0x200
PROM_HALF = 0x100


def read_exact(path, size, label):
    data = path.read_bytes()
    if len(data) != size:
        raise ValueError(f"{label}: {path} is {len(data)} bytes, expected {size}")
    return data


def compute_channel(inputs):
    conductance = 1.0 / 100.0 + 1.0 / 270.0
    current = 5.0 / 100.0
    if (inputs & 0x01) == 0:
        conductance += 1.0 / 270.0
        current += 0.05 / 270.0
    if (inputs & 0x02) == 0:
        conductance += 1.0
        current += 0.05
    return int((current / conductance) * 255.0 / 5.0 + 0.4)


def clamp(value):
    return min(255, max(0, value))


def decode_palette(prom_a, prom_b):
    raw = []
    luminance = []
    for address in range(128):
        low = prom_b[address]
        high = prom_a[address]
        red = compute_channel((low & 0x01) | ((high & 0x01) << 1))
        green = compute_channel(((low >> 2) & 0x01) | (((high >> 2) & 0x01) << 1))
        blue = compute_channel(((low >> 1) & 0x01) | (((high >> 1) & 0x01) << 1))
        raw.append((red, green, blue))
        luminance.append(299 * red + 587 * green + 114 * blue)

    minimum = min(luminance)
    maximum = max(luminance)
    palette = []
    for (red, green, blue), value in zip(raw, luminance):
        u = (blue - value // 1000) * 492 // 1000
        v = (red - value // 1000) * 877 // 1000
        target = ((value - minimum) * 256) // (maximum - minimum)
        palette.append((
            clamp(target + 1140 * v // 1000),
            clamp(target - 395 * u // 1000 - 581 * v // 1000),
            clamp(target + 2032 * u // 1000),
        ))
    return palette


def decode_tiles(gfx, offset):
    tiles = []
    for tile in range(256):
        pixels = []
        base = offset + tile * 8
        for row in range(8):
            low = gfx[base + row]
            high = gfx[base + 0x800 + row]
            for column in range(8):
                bit = 7 - column
                pixels.append(((high >> bit) & 1) << 1 | ((low >> bit) & 1))
        tiles.append(pixels)
    return tiles


def format_values(values, width=16):
    lines = []
    for offset in range(0, len(values), width):
        row = ", ".join(str(value) for value in values[offset:offset + width])
        lines.append(f"        {row},")
    return "\n".join(lines)


def enhance_tile(tile):
    """Create one C2-specific 16x16 glyph from an original 8x8 tile.

    Each output byte packs a two-bit palette index and full opacity.
    The glyph is stored in screen orientation, rather than the original
    hardware's rotated tile orientation.
    """
    source = [[0 for _ in range(16)] for _ in range(16)]

    def pixel(colour):
        return colour << 2 | 3

    for row in range(8):
        for column in range(8):
            colour = tile[row * 8 + column]
            if colour == 0:
                continue
            source[row * 2][column * 2] = pixel(colour)
            source[row * 2][column * 2 + 1] = pixel(colour)
            source[row * 2 + 1][column * 2] = pixel(colour)
            source[row * 2 + 1][column * 2 + 1] = pixel(colour)

    glyph = [0] * 256
    for row in range(16):
        for column in range(16):
            glyph[(15 - column) * 16 + (15 - row)] = source[row][column]
    return glyph


def render_glyphs(output, name, tiles):
    output.append(f"static const uint8_t {name}[256][256] = {{")
    for pixels in tiles:
        output.append("    {")
        output.append(format_values(pixels))
        output.append("    },")
    output.extend(["};", ""])


def render_header(background_tiles, foreground_tiles, palette):
    output = [
        "/* Generated by tools/generate_hires_sprite_assets.py. Do not edit. */",
        "#ifndef C2_HIRES_SPRITE_ASSETS_H",
        "#define C2_HIRES_SPRITE_ASSETS_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct { uint8_t red; uint8_t green; uint8_t blue; } C2HiresColour;",
        "#define C2_HIRES_PIXEL_COLOUR(pixel) ((pixel) >> 2)",
        "#define C2_HIRES_PIXEL_OPACITY(pixel) ((pixel) & 0x03)",
        "",
    ]
    render_glyphs(output, "C2_HIRES_BACKGROUND_GLYPHS",
                  [enhance_tile(tile) for tile in background_tiles])
    render_glyphs(output, "C2_HIRES_FOREGROUND_GLYPHS",
                  [enhance_tile(tile) for tile in foreground_tiles])
    output.extend(["static const C2HiresColour C2_HIRES_PROM_COLOURS[128] = {"])
    for red, green, blue in palette:
        output.append(f"    {{{red}, {green}, {blue}}},")
    output.extend([
        "};",
        "",
        "#endif",
        "",
    ])
    return "\n".join(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--graphics", type=Path, required=True,
                        help="Path to graphics.rom (8192 bytes)")
    parser.add_argument("--proms", type=Path, required=True,
                        help="Path to proms.rom (512 bytes)")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    gfx = read_exact(args.graphics, GRAPHICS_SIZE, "graphics ROM")
    proms = read_exact(args.proms, PROMS_SIZE, "colour PROM ROM")
    # proms.rom stores the low colour bits first, then the high bits.
    prom_b = proms[:PROM_HALF]
    prom_a = proms[PROM_HALF:]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_header(decode_tiles(gfx, 0x0000),
                                         decode_tiles(gfx, 0x1000),
                                         decode_palette(prom_a, prom_b)),
                           encoding="ascii")


if __name__ == "__main__":
    main()
